// Build the static site for GitHub Pages into dist/.
//
// The published site is network-mode only and has no backend: config.js is rewritten to
// static mode, and the historical-validation assets (which depend on the private City of
// Austin inspection records) are deliberately never copied.
//
// Deliberately dependency-free so CI needs nothing but a Node runtime.

import { cp, mkdir, rm, writeFile, readFile, stat } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'prediction_system', 'web_interface');
const DIST = join(ROOT, 'dist');

const CUSTOM_DOMAIN = 'try.wiltcast.com';

// Everything the static site needs. Anything not listed here does not ship.
const ASSETS = [
    'live_inference.html',
    'live_inference.js',
    'gbm.js',
    'simulation.js',
    'model/gbm_pressure.json'
];

const STATIC_CONFIG = `// Generated by scripts/build.mjs -- do not edit.
window.WILTCAST_CONFIG = {
    mode: 'static',
    modelUrl: 'model/gbm_pressure.json'
};
`;

async function exists(p) {
    try { await stat(p); return true; } catch { return false; }
}

async function main() {
    const modelPath = join(SRC, 'model', 'gbm_pressure.json');
    if (!await exists(modelPath)) {
        console.error(
            'Missing prediction_system/web_interface/model/gbm_pressure.json\n' +
            'Generate it first:  python prediction_system/export_model_json.py'
        );
        process.exit(1);
    }

    await rm(DIST, { recursive: true, force: true });
    await mkdir(DIST, { recursive: true });

    for (const asset of ASSETS) {
        const src = join(SRC, asset);
        const dest = join(DIST, asset);
        await mkdir(dirname(dest), { recursive: true });
        await cp(src, dest);
    }

    // The entry point is index.html; the original filename stays as a copy so existing
    // links to /live_inference.html keep working.
    const html = await readFile(join(SRC, 'live_inference.html'), 'utf8');
    await writeFile(join(DIST, 'index.html'), html);

    // GitHub Pages serves 404.html for unknown paths; serving the app makes any stale
    // deep link land on the tool rather than a Pages error page.
    await writeFile(join(DIST, '404.html'), html);

    await writeFile(join(DIST, 'config.js'), STATIC_CONFIG);
    await writeFile(join(DIST, 'CNAME'), `${CUSTOM_DOMAIN}\n`);

    // Without this, Pages runs the output through Jekyll, which strips paths beginning
    // with an underscore.
    await writeFile(join(DIST, '.nojekyll'), '');

    const modelKb = (await stat(modelPath)).size / 1024;
    console.log(`Built dist/ for ${CUSTOM_DOMAIN} (model ${modelKb.toFixed(0)} KB)`);
}

main();
